name: NATO Taleo Checker

on:
  schedule:
    - cron: "0 */3 * * *"   # her 3 saatte bir çalışır
  workflow_dispatch:        # manuel tetikleme imkanı

permissions:
  contents: write           # seen_jobs.json commit'i için
  issues: write             # issue oluşturmak/yorumlamak için

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları al
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Chrome kur
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Script'i çalıştır
        env:
          CHROME_PATH: ${{ env.CHROME_PATH }}
          CHROME_BIN: ${{ env.CHROME_BIN }}
        run: |
          python nato_taleo_alert.py

      - name: Yeni ilan varsa issue/yorum oluştur
        if: hashFiles('alert.md') != ''
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('alert.md', 'utf8');
            const title = 'NATO Taleo Alerts';

            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            let issue = issues.find(i => i.title === title);

            if (!issue) {
              const resp = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title,
                body: 'Bu issue altına yeni ilanlar yorum olarak eklenecek.',
                assignees: ['anthrozz']
              });
              issue = resp.data;
            } else {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                assignees: ['anthrozz']
              });
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body
            });

      - name: Değişiklikleri commit/push et (seen_jobs.json)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update seen_jobs.json [skip ci]"
            git push
          fi
